import "./globals.css";

import { cx } from "class-variance-authority";
import { Inter } from "next/font/google";

import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test to use wagmi viem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          "relative flex h-full flex-col overflow-hidden rounded-3xl bg-gradient-to-tl from-rose-400 via-gray-600 to-gray-900 bg-no-repeat"
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
